# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greedy', '0003_auto_20160423_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Tracks'},
        ),
        migrations.AddField(
            model_name='genre',
            name='context',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
